# coding: utf-8

"""
    UrlShortener API

    Description  # noqa: E501

    OpenAPI spec version: v1
    Contact: gagarinovdaniil@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DetailApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def detail_delete(self, short_url, **kwargs):  # noqa: E501
        """detail_delete  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detail_delete(short_url, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str short_url: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.detail_delete_with_http_info(short_url, **kwargs)  # noqa: E501
        else:
            (data) = self.detail_delete_with_http_info(short_url, **kwargs)  # noqa: E501
            return data

    def detail_delete_with_http_info(self, short_url, **kwargs):  # noqa: E501
        """detail_delete  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detail_delete_with_http_info(short_url, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str short_url: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['short_url']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method detail_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'short_url' is set
        if self.api_client.client_side_validation and ('short_url' not in params or
                                                       params['short_url'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `short_url` when calling `detail_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'short_url' in params:
            path_params['short_url'] = params['short_url']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '/detail/{short_url}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def detail_partial_update(self, short_url, data, **kwargs):  # noqa: E501
        """detail_partial_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detail_partial_update(short_url, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str short_url: (required)
        :param Url data: (required)
        :return: Url
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.detail_partial_update_with_http_info(short_url, data, **kwargs)  # noqa: E501
        else:
            (data) = self.detail_partial_update_with_http_info(short_url, data, **kwargs)  # noqa: E501
            return data

    def detail_partial_update_with_http_info(self, short_url, data, **kwargs):  # noqa: E501
        """detail_partial_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detail_partial_update_with_http_info(short_url, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str short_url: (required)
        :param Url data: (required)
        :return: Url
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['short_url', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method detail_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'short_url' is set
        if self.api_client.client_side_validation and ('short_url' not in params or
                                                       params['short_url'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `short_url` when calling `detail_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if self.api_client.client_side_validation and ('data' not in params or
                                                       params['data'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `data` when calling `detail_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'short_url' in params:
            path_params['short_url'] = params['short_url']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '/detail/{short_url}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Url',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def detail_read(self, short_url, **kwargs):  # noqa: E501
        """detail_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detail_read(short_url, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str short_url: (required)
        :return: Url
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.detail_read_with_http_info(short_url, **kwargs)  # noqa: E501
        else:
            (data) = self.detail_read_with_http_info(short_url, **kwargs)  # noqa: E501
            return data

    def detail_read_with_http_info(self, short_url, **kwargs):  # noqa: E501
        """detail_read  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detail_read_with_http_info(short_url, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str short_url: (required)
        :return: Url
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['short_url']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method detail_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'short_url' is set
        if self.api_client.client_side_validation and ('short_url' not in params or
                                                       params['short_url'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `short_url` when calling `detail_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'short_url' in params:
            path_params['short_url'] = params['short_url']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '/detail/{short_url}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Url',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def detail_update(self, short_url, data, **kwargs):  # noqa: E501
        """detail_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detail_update(short_url, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str short_url: (required)
        :param Url data: (required)
        :return: Url
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.detail_update_with_http_info(short_url, data, **kwargs)  # noqa: E501
        else:
            (data) = self.detail_update_with_http_info(short_url, data, **kwargs)  # noqa: E501
            return data

    def detail_update_with_http_info(self, short_url, data, **kwargs):  # noqa: E501
        """detail_update  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.detail_update_with_http_info(short_url, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str short_url: (required)
        :param Url data: (required)
        :return: Url
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['short_url', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method detail_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'short_url' is set
        if self.api_client.client_side_validation and ('short_url' not in params or
                                                       params['short_url'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `short_url` when calling `detail_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if self.api_client.client_side_validation and ('data' not in params or
                                                       params['data'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `data` when calling `detail_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'short_url' in params:
            path_params['short_url'] = params['short_url']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '/detail/{short_url}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Url',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
