# coding: utf-8

"""
    UrlShortener API

    Description  # noqa: E501

    OpenAPI spec version: v1
    Contact: gagarinovdaniil@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.url import Url  # noqa: E501
from swagger_client.rest import ApiException


# self, short_url=None, full_url=None, creator=None, date_created=None, used=None, _configuration=None):

class TestUrl(unittest.TestCase):
    """Url unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUrl(self):
        """Test Url"""
        model = swagger_client.models.url.Url('test', 'full_test', None, 0)
        self.assertEqual(model.short_url, 'test')


if __name__ == '__main__':
    unittest.main()
