# coding: utf-8

"""
    UrlShortener API

    Description  # noqa: E501

    OpenAPI spec version: v1
    Contact: gagarinovdaniil@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.detail_api import DetailApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDetailApi(unittest.TestCase):
    """DetailApi unit test stubs"""

    def setUp(self):
        configuration = swagger_client.Configuration()
        configuration.username = 'yaishenka'
        configuration.password = 'root'
        self.detail_api = swagger_client.api.detail_api.DetailApi(swagger_client.ApiClient(configuration))  # noqa: E501
        self.manage_api = swagger_client.api.manage_api.ManageApi(swagger_client.ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        self.detail_api.detail_delete(short_url='test')


    def test_detail_partial_update(self):
        """Test case for detail_partial_update

        """
        data = {'full_url': 'full_test', 'short_url': 'test'}
        self.manage_api.manage_create(data)
        self.detail_api.detail_update('test', {'short_url': 'test', 'full_url': 'new_url'})
        new_url = self.detail_api.detail_read('test')
        self.assertEqual(new_url.full_url, 'new_url')

    def test_detail_read(self):
        data = {'full_url': 'full_test', 'short_url': 'test'}
        self.manage_api.manage_create(data)
        url = self.detail_api.detail_read('test')
        self.assertEqual(url.full_url, 'full_test')


if __name__ == '__main__':
    unittest.main()
